# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  bkecanet:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-udn
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.udn.bkeca.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ef80b6a967c7ef0e99d351de75a133ee5104c3c9f41da5eb6e11b41fb13b5cd1_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.udn.bkeca.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ef80b6a967c7ef0e99d351de75a133ee5104c3c9f41da5eb6e11b41fb13b5cd1_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/udn.bkeca.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerudn
    networks:
      - bkecanet

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dut
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.dut.bkeca.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fa554665f4bf37249e3f0f965befaf77068c053ba0616891ce6392c31ec28569_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.dut.bkeca.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/fa554665f4bf37249e3f0f965befaf77068c053ba0616891ce6392c31ec28569_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/dut.bkeca.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerdut
    networks:
      - bkecanet