# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.bkeca.com:
    container_name: orderer.bkeca.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/bkeca.com/orderers/orderer.bkeca.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/bkeca.com/orderers/orderer.bkeca.com/tls/:/var/hyperledger/orderer/tls
        - orderer.bkeca.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.udn.bkeca.com:
    container_name: peer0.udn.bkeca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.udn.bkeca.com
      - CORE_PEER_ADDRESS=peer0.udn.bkeca.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.udn.bkeca.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.udn.bkeca.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.udn.bkeca.com:7051
      - CORE_PEER_LOCALMSPID=UdnMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/udn.bkeca.com/peers/peer0.udn.bkeca.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/udn.bkeca.com/peers/peer0.udn.bkeca.com/tls:/etc/hyperledger/fabric/tls
        - peer0.udn.bkeca.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.udn.bkeca.com:
    container_name: peer1.udn.bkeca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.udn.bkeca.com
      - CORE_PEER_ADDRESS=peer1.udn.bkeca.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.udn.bkeca.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.udn.bkeca.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.udn.bkeca.com:7051
      - CORE_PEER_LOCALMSPID=UdnMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/udn.bkeca.com/peers/peer1.udn.bkeca.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/udn.bkeca.com/peers/peer1.udn.bkeca.com/tls:/etc/hyperledger/fabric/tls
        - peer1.udn.bkeca.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.dut.bkeca.com:
    container_name: peer0.dut.bkeca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dut.bkeca.com
      - CORE_PEER_ADDRESS=peer0.dut.bkeca.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dut.bkeca.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dut.bkeca.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dut.bkeca.com:10051
      - CORE_PEER_LOCALMSPID=DutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dut.bkeca.com/peers/peer0.dut.bkeca.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dut.bkeca.com/peers/peer0.dut.bkeca.com/tls:/etc/hyperledger/fabric/tls
        - peer0.dut.bkeca.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.dut.bkeca.com:
    container_name: peer1.dut.bkeca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dut.bkeca.com
      - CORE_PEER_ADDRESS=peer1.dut.bkeca.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dut.bkeca.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dut.bkeca.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dut.bkeca.com:9051
      - CORE_PEER_LOCALMSPID=DutMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dut.bkeca.com/peers/peer1.dut.bkeca.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dut.bkeca.com/peers/peer1.dut.bkeca.com/tls:/etc/hyperledger/fabric/tls
        - peer1.dut.bkeca.com:/var/hyperledger/production
    ports:
      - 10051:10051
